drop table if exists urls CASCADE;
create table urls
(
 id bigint generated by default as identity,
 originalUrl varchar(255),
 shortenedUrl varchar(255),
 primary key (id)
);
insert into Urls values(5,'a','b');